INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('1', 'unknown', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('2', 'Pogodnie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('3', 'Bezchmurnie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('4', 'Przewaznie pogodnie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('5', 'Przewaznie bezchmurnie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('6', 'Zamglone slonce', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('7', 'Mgla', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('8', 'Przelotne zachmurzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('9', 'Przewaga slonca nad chmurami', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('10', 'Rozproszone chmury', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('11', 'Polowiczne zachmurzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('12', 'Slonce i chmury', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('13', 'Wysokie chmur', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('14', 'Przewaga chmur nad sloncem', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('15', 'Polowicznie slonecznie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('16', 'Rozbite chmury', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('17', 'Przewaznie pochmurno', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('18', 'Chmury', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('19', 'Pochmurno', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('20', 'Niskie chmury', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('21', 'Lekka mgla', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('22', 'Mgla', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('23', 'Gesta mgla', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('24', 'Mgla lodowa', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('25', 'Burza piaskowa', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('26', 'Burza pylu', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('27', 'Zwiekaszajace sie zachmurzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('28', 'Zmniejszajace sie zachmurzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('29', 'Rozpogodzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('30', 'Przeswity slonca', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('31', 'Wczesna mgla, po ktorej nastepuje rozpogodzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('32', 'Popoludniowe zachmurzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('33', 'Poranne zachmurzenie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('34', 'Upalnie', 'unknown');
INSERT INTO `Weather_Type` (`Id`, `Main`, `Description`) VALUES ('35', 'Niski poziom zamglenia', 'unknown');